/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#dbe1ff',
        'on-secondary': '#ffffff',
        'on-surface': '#0b1c30',
        'on-primary-container': '#7c839b',
        'secondary-container': '#316bf3',
        'surface-container': '#e5eeff',
        'on-tertiary-fixed-variant': '#005236',
        'on-tertiary-container': '#009668',
        'primary-container': '#131b2e',
        'surface': '#f8f9ff',
        'tertiary-fixed-dim': '#4edea3',
        'on-primary-fixed': '#131b2e',
        'secondary-fixed-dim': '#b4c5ff',
        'on-secondary-fixed-variant': '#003ea8',
        'on-primary-fixed-variant': '#3f465c',
        'tertiary-fixed': '#6ffbbe',
        'error': '#ba1a1a',
        'surface-bright': '#f8f9ff',
        'on-secondary-container': '#fefcff',
        'surface-tint': '#565e74',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#bec6e0',
        'on-tertiary-fixed': '#002113',
        'on-error-container': '#93000a',
        'surface-container-low': '#eff4ff',
        'on-secondary-fixed': '#00174b',
        'outline': '#76777d',
        'primary-fixed': '#dae2fd',
        'surface-dim': '#cbdbf5',
        'on-primary': '#ffffff',
        'on-background': '#0b1c30',
        'tertiary-container': '#002113',
        'surface-container-high': '#dce9ff',
        'background': '#f8f9ff',
        'surface-variant': '#d3e4fe',
        'tertiary': '#000000',
        'primary': '#000000',
        'surface-container-highest': '#d3e4fe',
        'outline-variant': '#c6c6cd',
        'secondary': '#0051d5',
        'inverse-surface': '#213145',
        'inverse-primary': '#bec6e0',
        'on-surface-variant': '#45464d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        xl: '64px',
        md: '24px',
        gutter: '24px',
        base: '8px',
        margin: '32px',
        lg: '40px',
        sm: '12px',
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'stat-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
